"""empty message

Revision ID: 72f6bdf410e2
Revises: 34fed1a16047
Create Date: 2021-02-27 17:44:56.804659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72f6bdf410e2'
down_revision = '34fed1a16047'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('book_id', sa.Integer(), nullable=True))
    op.add_column('comment', sa.Column('date', sa.DateTime(), nullable=True))
    op.add_column('comment', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'book', ['book_id'], ['id'])
    op.create_foreign_key(None, 'comment', 'user', ['user_id'], ['id'])
    op.drop_column('comment', 'bookid')
    op.drop_column('comment', 'create_date')
    op.drop_column('comment', 'userid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('userid', sa.INTEGER(), nullable=True))
    op.add_column('comment', sa.Column('create_date', sa.DATETIME(), nullable=True))
    op.add_column('comment', sa.Column('bookid', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'book', ['bookid'], ['id'])
    op.create_foreign_key(None, 'comment', 'user', ['userid'], ['id'])
    op.drop_column('comment', 'user_id')
    op.drop_column('comment', 'date')
    op.drop_column('comment', 'book_id')
    # ### end Alembic commands ###
